{% set name = "kivy-garden" %}
{% set version = "0.1.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/Kivy Garden-{{ version }}.tar.gz
  sha256: 2b8377378e87501d5d271f33d94f0e44c089884572c64f89c9d609b1f86a2748

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python
    - pip
    - ez_setup
  run:
    - python
    - pip
    - requests

test:
  imports:
    - garden
  commands:
    - pip check

about:
  home: https://github.com/kivy-garden/garden
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'The kivy garden installation script, split into its own package for convenient use in buildozer.'

  description: |
    The kivy garden installation script, split into its own package for 
    convenient use in buildozer.
  doc_url: https://github.com/kivy-garden/garden
  dev_url: https://github.com/kivy-garden/garden

extra:
  recipe-maintainers:
    - jan-janssen
